[package]
name = "adblock-rust-dashboard"
version = "0.1.0"
authors = ["Anton Lazarev <alazarev@brave.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
yew = "^ 0.17"
wasm-bindgen = "^ 0.2"
web-sys = "^ 0.3"
console_error_panic_hook = "^ 0.1"

adblock = "0.3.3"
